version: "3.6"

services:

  voting:
    image: dansolo7/voting:1.0
    environment:
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
