apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:{{ .Values.mysql.version }}
        name: mysql
        env:
        - name: MYSQL_HOST
          value: {{ .Values.mysql.MYSQL_HOST }}

        - name: MYSQL_USER
          value: {{ .Values.mysql.MYSQL_USER }}

        - name: MYSQL_DB
          value: {{ .Values.mysql.MYSQL_DB }}

        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-voteapp-secret
              key: mysql_password
        ports:
        - containerPort: 3306
          name: mysql
