apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-crb-vote
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-cr-vote
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-vote-service-account
  namespace: {{ .Values.KUBERNETES_NAMESPACE }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-crb-worker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-cr-worker
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-worker-service-account
  namespace: {{ .Values.KUBERNETES_NAMESPACE }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-crb-front
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-cr-front
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-front-service-account
  namespace: {{ .Values.KUBERNETES_NAMESPACE }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-rbc-mysql
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-cr-mysql
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-mysql-service-account
  namespace: {{ .Values.KUBERNETES_NAMESPACE }}
