apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.KUBERNETES_NAMESPACE }}
  name: mysql-service
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP