apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.KUBERNETES_NAMESPACE }}
  name: {{ .Release.Name }}-voteapp-secret
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  aws_access_key: {{ .Values.passwords.AWS_ACCESS_KEY | b64enc }}
  aws_secret_key: {{ .Values.passwords.AWS_SECRET_KEY | b64enc }}
  mysql_password: {{ .Values.passwords.MYSQL_PASSWORD | b64enc }}
