apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Values.KUBERNETES_NAMESPACE }}
  name: {{ .Release.Name }}-vote-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/default-backend: default/defaultbackend-service
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: www.vote.com
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-vote-service # Selecting Service
            servicePort: 80
