apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.KUBERNETES_NAMESPACE }}
  annotations:
  labels:
    run: vote
  name: {{ .Release.Name }}-vote-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: vote
  template:
    metadata:
      labels:
        run: vote
    spec:
      containers:
      - image: dansolo7/voting:{{ .Values.vote.version }}
        imagePullPolicy: Always
        name: vote
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        env:
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-voteapp-secret
              key: aws_access_key
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-voteapp-secret
              key: aws_secret_key
        - name: AWS_REGION
          value: {{ .Values.vote.AWS_REGION }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
