apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.KUBERNETES_NAMESPACE }}
  labels:
    run: worker
  name: {{ .Release.Name }}-worker-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80 # Criada para intra cluster. Para Fazer o bind
    protocol: TCP
    targetPort: 80 # Porta do container
  selector:
    run: worker
  sessionAffinity: None
  type: NodePort
